insert into sy_resource(RESOURCECODE,RESOURCETEXT,WEBURL,RESOURCETYPEECODE,LOCKFLAG,CREATEUSER,CREATEDATETIME,MODIFYUSER,MODIFYDATETIME)
values ('${bean.className}','${bean.comment}','/manage/${bean.className?uncap_first}/list','FORM','0','SA',SYSDATE(),'SA',SYSDATE());
insert into sy_resource(RESOURCECODE,RESOURCETEXT,RESOURCETYPEECODE,LOCKFLAG,CREATEUSER,CREATEDATETIME,MODIFYUSER,MODIFYDATETIME)
values ('${bean.className}_ADD','${bean.comment}新增','BUTN','0','SA',SYSDATE(),'SA',SYSDATE());
insert into sy_resource(RESOURCECODE,RESOURCETEXT,RESOURCETYPEECODE,LOCKFLAG,CREATEUSER,CREATEDATETIME,MODIFYUSER,MODIFYDATETIME)
values ('${bean.className}_DEL','${bean.comment}删除','BUTN','0','SA',SYSDATE(),'SA',SYSDATE());
insert into sy_resource(RESOURCECODE,RESOURCETEXT,RESOURCETYPEECODE,LOCKFLAG,CREATEUSER,CREATEDATETIME,MODIFYUSER,MODIFYDATETIME)
values ('${bean.className}_EDIT','${bean.comment}修改','BUTN','0','SA',SYSDATE(),'SA',SYSDATE());

insert into sy_menu(MENUCODE,MENUTEXT,PARENTMENUCODE,RESOURCECODE,DISPLAYORDINAL,LOCKFLAG,CREATEUSER,CREATEDATETIME,MODIFYUSER,MODIFYDATETIME,SITECODE)
values('${bean.className}','${bean.comment}','?','${bean.className}','1','0','SA',SYSDATE(),'SA',SYSDATE(),'1001');
insert into sy_menu(MENUCODE,MENUTEXT,PARENTMENUCODE,RESOURCECODE,DISPLAYORDINAL,LOCKFLAG,CREATEUSER,CREATEDATETIME,MODIFYUSER,MODIFYDATETIME,SITECODE)
values('${bean.className}_ADD','${bean.comment}新增','${bean.className}','${bean.className}_ADD','1','0','SA',SYSDATE(),'SA',SYSDATE(),'1001');
insert into sy_menu(MENUCODE,MENUTEXT,PARENTMENUCODE,RESOURCECODE,DISPLAYORDINAL,LOCKFLAG,CREATEUSER,CREATEDATETIME,MODIFYUSER,MODIFYDATETIME,SITECODE)
values('${bean.className}_DEL','${bean.comment}删除','${bean.className}','${bean.className}_DEL','1','0','SA',SYSDATE(),'SA',SYSDATE(),'1001');
insert into sy_menu(MENUCODE,MENUTEXT,PARENTMENUCODE,RESOURCECODE,DISPLAYORDINAL,LOCKFLAG,CREATEUSER,CREATEDATETIME,MODIFYUSER,MODIFYDATETIME,SITECODE)
values('${bean.className}_EDIT','${bean.comment}修改','${bean.className}','${bean.className}_EDIT','1','0','SA',SYSDATE(),'SA',SYSDATE(),'1001');
